;; -*- lexical-binding: t -*-

(set-face-attribute 'default nil :family "Iosevka SS08" :height 190)
(set-face-attribute 'fixed-pitch nil :family "Iosevka SS08" :height 190)
(set-face-attribute 'variable-pitch nil :family "Iosevka SS08" :height 190)

(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(setq package-archive-priorities
      '(("gnu"           . 99)
        ("nongnu"        . 80)
        ("melpa-stable"  . 60)
        ("melpa"         . 40))
      package-install-upgrade-built-in t)
(when package-enable-at-startup (package-initialize))
(unless package-archive-contents (package-refresh-contents))
(add-to-list 'display-buffer-alist
             '("\\`\\*\\(Warnings\\|Compile-Log\\)\\*\\'"
               (display-buffer-no-window)
               (allow-no-window . t)))

(add-to-list 'load-path (expand-file-name "site-lisp" no-littering-etc-directory))
(require 'setup-emacs)
(require 'setup-keymaps)
(require 'setup-dired)
(require 'setup-recentf)
(require 'setup-eshell)
(require 'setup-docker)
(require 'setup-zig-mode)
(require 'setup-haskell-mode)
(require 'setup-markdown-mode)
(require 'setup-pyvenv)
(require 'setup-eglot)
(require 'setup-themes)
(require 'setup-diff-hl)
(require 'setup-evil)
(require 'setup-vertico)
(require 'setup-corfu)
(require 'setup-consult)
(require 'setup-embark)
(require 'setup-wgrep)
(require 'setup-orderless)
(require 'setup-marginalia)
(require 'setup-avy)
(require 'setup-magit)
(require 'setup-ace-window)
(require 'setup-denote)
(require 'setup-org)
